name: Certora Tests

on:
  push:
    branches:
      - main
      - main-v*
  pull_request:
    branches:
      - main
      - main-v*
      - v*
  workflow_dispatch:

permissions:
  contents: read
  statuses: write
  pull-requests: write
  id-token: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Tests
        run: nix develop --impure --command make check

  fail_to_start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - name: Fail to Start
        uses: ./
        with:
          cli-release: beta
          configurations: |-
            tests/evm/conf-start-error.conf
            tests/evm/conf-verified.conf --rule monotone --method "counter()"
            tests/evm/conf-violations.conf --method "counter()"
            tests/evm/conf-verified.conf
            tests/evm/conf-violations.conf --rule invertible
            tests/evm/conf-start-error.conf --method "counter()"
          solc-versions: 0.7.6 0.8.1
          job-name: "Fail to Start"
          server: "staging"
          debug-level: 3
          certora-key: ${{ secrets.CERTORAKEY }}
          vyper-version: latest
        id: certora_run
        continue-on-error: true
      - name: Check if Fail to Start job failed
        if: steps.certora_run.outcome != 'failure'
        run: |
          echo "Fail to Start job did not fail"
          exit 1

  violated_rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - name: Violated Rules
        uses: ./
        with:
          configurations: |-
            tests/evm/conf-verified.conf
            tests/evm/conf-violations.conf --rule invertible
            tests/evm/conf-verified.conf --method "counter()"
            tests/evm/conf-violations.conf
          solc-versions: 0.7.6 0.8.1
          job-name: "Violated Rules"
          server: "production"
          debug-level: 3
          certora-key: ${{ secrets.CERTORAKEY }}

  verified_rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - name: Verified Rules
        uses: ./
        with:
          configurations: |-
            tests/evm/conf-verified.conf
            tests/evm/conf-verified.conf --rule monotone --method "counter()"
            tests/evm/conf-verified.conf --rule invertible
            tests/evm/conf-verified.conf --method "counter()"
          solc-versions: 0.7.6 0.8.1
          job-name: "Verified Rules"
          server: "vaas-dev"
          debug-level: 3
          certora-key: ${{ secrets.CERTORAKEY }}

  solana-violated-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Solana Violated Rules
        uses: ./
        with:
          working-directory: tests/solana
          ecosystem: solana
          configurations: |-
            Default.conf
          job-name: "Solana Violated Rules"
          server: "staging"
          debug-level: 3
          certora-key: ${{ secrets.CERTORAKEY }}

  sui-verified-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Sui CLI
        run: |
          sui_cli_version="testnet-v1.60.0"
          sui_cli_os="ubuntu-x86_64"
          sui_bin_path="$HOME/.local/bin"

          mkdir -p "$sui_bin_path"
          curl -LO  "https://github.com/MystenLabs/sui/releases/download/$sui_cli_version/sui-$sui_cli_version-$sui_cli_os.tgz"
          tar -xzf sui-$sui_cli_version-$sui_cli_os.tgz -C "$sui_bin_path" ./sui
          export PATH="$sui_bin_path:$PATH"
      - name: Sui Verified Rules
        uses: ./
        with:
          working-directory: tests/sui
          ecosystem: sui
          cli-release: beta
          configurations: |-
            Hello.conf
          job-name: "Sui Violated Rules"
          server: "staging"
          debug-level: 3
          certora-key: ${{ secrets.CERTORAKEY }}

  soroban-verified-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run configs
        uses: ./
        with:
          working-directory: tests/soroban
          ecosystem: soroban
          cli-release: stable
          configurations: |-
            simple.conf
          job-name: "Soroban rule"
          server: "staging"
          debug-level: 3
          certora-key: ${{ secrets.CERTORAKEY }}
